baseURL: https://scipy.org/
languageCode: en-us
theme: scientific-python-hugo-theme
disableKinds:
  - taxonomy
  - term
DefaultContentLanguage: en
markup:
  goldmark:
    renderer:
      unsafe: true
disableLanguages: []
params:
  images:
    - /images/logo.svg
  navColor: blue
  font:
    name: Lato
    sizes:
      - 400
      - 900
  plausible:
    dataDomain: scipy.org
languages:
  en:
    title: SciPy
    weight: 1
    contentDir: content/en
    languageName: English
    params:
      description:
        Why SciPy? Fundamental algorithms. Broadly applicable. Foundational.
        Interoperable. Performant. Open source.
      navbarlogo:
        image: logo.svg
        altText: A blue circle with a snake in the shape of the letter 'S'.
        text: SciPy
        link: /
      hero:
        title: SciPy
        subtitle: Fundamental algorithms for scientific computing in Python
        buttontext: Get started
        buttonlink: /install
        image: logo.svg
      section5: false
      navbar:
        - title: Install
          url: /install
        - title: Documentation
          url: https://docs.scipy.org/doc/scipy/
        - title: Community
          url: /community
        - title: About Us
          url: /about
        - title: Contribute
          url: /contribute
      footer:
        logo: logo.svg
        socialmediatitle: ""
        socialmedia:
          - link: https://github.com/scipy/scipy
            icon: github
          - link: https://discuss.scientific-python.org/c/contributor/scipy/
            icon: scientific-python
        quicklinks:
          column1:
            title: ""
            links:
              - text: Install
                link: /install
              - text: Documentation
                link: https://docs.scipy.org/doc/scipy/
              - text: Citing SciPy
                link: /citing-scipy
              - text: Roadmap
                link: https://scipy.github.io/devdocs/dev/roadmap.html
          column2:
            links:
              - text: About Us
                link: /about
              - text: Community
                link: /community
              - text: SciPy Conference
                link: https://conference.scipy.org/
              - text: Contribute
                link: /contribute
              - text: Code of Conduct
                link: https://docs.scipy.org/doc/scipy/dev/conduct/code_of_conduct.html
          column3:
            links:
              - text: FAQ
                link: /faq
              - text: Terms of Use
                link: /terms
              - text: Privacy
                link: /privacy
              - text: Press Kit
                link: /press-kit
              - text: Social Media
                link: /about/#social-media
  es:
    title: SciPy
    weight: 3
    contentDir: content/es
    languageName: "Espa\xF1ol"
    params:
      description:
        Why SciPy? Fundamental algorithms. Broadly applicable. Foundational.
        Interoperable. Performant. Open source.
      navbarlogo:
        image: logo.svg
        altText: A blue circle with a snake in the shape of the letter 'S'.
        text: SciPy
        link: /es/
      hero:
        title: SciPy
        subtitle: Fundamental algorithms for scientific computing in Python
        buttontext: Get started
        buttonlink: /es/install
        image: logo.svg
      section5: false
      navbar:
        - title: Install
          url: /es/install
        - title: Documentation
          url: https://docs.scipy.org/doc/scipy/
        - title: Community
          url: /es/community
        - title: About Us
          url: /es/about
        - title: Contribute
          url: /es/contribute
      footer:
        logo: logo.svg
        socialmediatitle: ""
        socialmedia:
          - link: https://github.com/scipy/scipy
            icon: github
          - link: https://discuss.scientific-python.org/c/contributor/scipy/
            icon: scientific-python
        quicklinks:
          column1:
            title: ""
            links:
              - text: Install
                link: /es/install
              - text: Documentation
                link: https://docs.scipy.org/doc/scipy/
              - text: Citing SciPy
                link: /es/citing-scipy
              - text: Roadmap
                link: https://scipy.github.io/devdocs/dev/roadmap.html
          column2:
            links:
              - text: About Us
                link: /es/about
              - text: Community
                link: /es/community
              - text: SciPy Conference
                link: https://conference.scipy.org/
              - text: Contribute
                link: /es/contribute
              - text: Code of Conduct
                link: https://docs.scipy.org/doc/scipy/dev/conduct/code_of_conduct.html
          column3:
            links:
              - text: FAQ
                link: /es/faq
              - text: Terms of Use
                link: /es/terms
              - text: Privacy
                link: /es/privacy
              - text: Press Kit
                link: /es/press-kit
              - text: Social Media
                link: /es/about/#social-media
  ja:
    title: SciPy
    weight: 4
    contentDir: content/ja
    languageName: Japanese
    params:
      description:
        Why SciPy? Fundamental algorithms. Broadly applicable. Foundational.
        Interoperable. Performant. Open source.
      navbarlogo:
        image: logo.svg
        altText: A blue circle with a snake in the shape of the letter 'S'.
        text: SciPy
        link: /ja/
      hero:
        title: SciPy
        subtitle: Fundamental algorithms for scientific computing in Python
        buttontext: Get started
        buttonlink: /ja/install
        image: logo.svg
      section5: false
      navbar:
        - title: Install
          url: /ja/install
        - title: Documentation
          url: https://docs.scipy.org/doc/scipy/
        - title: Community
          url: /ja/community
        - title: About Us
          url: /ja/about
        - title: Contribute
          url: /ja/contribute
      footer:
        logo: logo.svg
        socialmediatitle: ""
        socialmedia:
          - link: https://github.com/scipy/scipy
            icon: github
          - link: https://discuss.scientific-python.org/c/contributor/scipy/
            icon: scientific-python
        quicklinks:
          column1:
            title: ""
            links:
              - text: Install
                link: /ja/install
              - text: Documentation
                link: https://docs.scipy.org/doc/scipy/
              - text: Citing SciPy
                link: /ja/citing-scipy
              - text: Roadmap
                link: https://scipy.github.io/devdocs/dev/roadmap.html
          column2:
            links:
              - text: About Us
                link: /ja/about
              - text: Community
                link: /ja/community
              - text: SciPy Conference
                link: https://conference.scipy.org/
              - text: Contribute
                link: /ja/contribute
              - text: Code of Conduct
                link: https://docs.scipy.org/doc/scipy/dev/conduct/code_of_conduct.html
          column3:
            links:
              - text: FAQ
                link: /ja/faq
              - text: Terms of Use
                link: /ja/terms
              - text: Privacy
                link: /ja/privacy
              - text: Press Kit
                link: /ja/press-kit
              - text: Social Media
                link: /ja/about/#social-media
  pt:
    title: SciPy
    weight: 2
    contentDir: content/pt
    languageName: "Portugu\xEAs"
    params:
      description:
        "Por que SciPy? Algoritmos fundamentais. Amplas aplica\xE7\xF5\
        es. Fundamental. Interoper\xE1vel. Alto desempenho. Open source."
      navbarlogo:
        image: logo.svg
        altText: A blue circle with a snake in the shape of the letter 'S'.
        text: SciPy
        link: /pt/
      hero:
        title: SciPy
        subtitle:
          "Algoritmos fundamentais para computa\xE7\xE3o cient\xEDfica com\
          \ Python"
        buttontext: Comece aqui
        buttonlink: /pt/install
        image: logo.svg
      section5: false
      navbar:
        - title: Instalar
          url: /pt/install
        - title: "Documenta\xE7\xE3o"
          url: https://docs.scipy.org/doc/scipy/
        - title: Comunidade
          url: /pt/community
        - title: Quem somos
          url: /pt/about
        - title: Contribuir
          url: /pt/contribute
      footer:
        logo: logo.svg
        socialmediatitle: ""
        socialmedia:
          - link: https://github.com/scipy/scipy
            icon: github
          - link: https://discuss.scientific-python.org/c/contributor/scipy/
            icon: scientific-python
        quicklinks:
          column1:
            title: ""
            links:
              - text: Instalar
                link: /pt/install
              - text: "Documenta\xE7\xE3o"
                link: https://docs.scipy.org/doc/scipy/
              - text: Citar a SciPy
                link: /pt/citing-scipy
              - text: Roadmap
                link: https://scipy.github.io/devdocs/dev/roadmap.html
          column2:
            links:
              - text: Quem somos
                link: /pt/about
              - text: Comunidade
                link: /pt/community
              - text: SciPy Conference
                link: https://conference.scipy.org/
              - text: Contribuir
                link: /pt/contribute
              - text: "C\xF3digo de Conduta (em ingl\xEAs)"
                link: https://docs.scipy.org/doc/scipy/dev/conduct/code_of_conduct.html
          column3:
            links:
              - text: FAQ
                link: /pt/faq
              - text: "Termos de Uso (em ingl\xEAs)"
                link: /pt/terms
              - text: Privacidade
                link: /pt/privacy
              - text: Kit de imprensa
                link: /pt/press-kit
              - text: "M\xEDdias Sociais"
                link: /pt/about/#social-media
