baseURL: https://scipy.scientific-python.org/
languageCode: en-us
theme: scientific-python-hugo-theme
disableKinds: ["taxonomy", "term"]
DefaultContentLanguage: en
markup:
  goldmark:
    renderer:
      unsafe: true

# Uncomment this to disable the translations for the specified languages.
# This may be useful to be able to merge partial translations without deploying
# them to scipy.org immediately.
# disableLanguages: ["pt", "ja"]

params:
  images:
  - /images/logo.svg
  navColor: blue
  font:
    name: "Lato"
    sizes: [400,900]

languages:
  en:
    title: SciPy
    weight: 1
    contentDir: content/en

    languageName: English
    params:
      description: Why SciPy? Fundamental algorithms. Broadly applicable. Foundational. Interoperable. Performant. Open source.
      navbarlogo:
        image: logo.svg
        altText: A blue circle with a snake in the shape of the letter 'S'.
        link: /
      hero:
        # Main hero title
        title: SciPy
        # Hero subtitle (optional)
        subtitle: Fundamental algorithms for scientific computing in Python
        # Button text
        buttontext: Get started
        # Where the main hero button links to
        buttonlink: "/install"
        # Hero image (from static/images/___)
        image: logo.svg
      # Customizable navbar. For a dropdown, add a "sublinks" list.
      news:
        title: SciPy 1.7.1 released
        content: 2021-08-01
        url: /news

      keyfeatures:
        features:
        - title: Fundamental algorithms
          text: SciPy provides algorithms for optimization, integration, interpolation, eigenvalue problems, algebraic equations, differential equations, statistics and many other classes of problems.
        - title: Broadly applicable
          text: The algorithms and data structures provided by SciPy are broadly applicable across domains.
        - title: Foundational
          text:  Extends NumPy providing additional tools for array computing and provides specialized data structures, such as sparse matrices and k-dimensional trees.
        - title: Performant
          text: SciPy wraps highly-optimized implementations written in low-level languages like Fortran, C, and C++. Enjoy the flexibility of Python with the speed of compiled code.
        - title: Easy to use
          text: SciPy's high level syntax makes it accessible and productive for programmers from any background or experience level.
        - title: Open source
          text: Distributed under a liberal [BSD license](https://github.com/scipy/scipy/blob/master/LICENSE.txt), SciPy is developed and maintained [publicly on GitHub](https://github.com/scipy/scipy) by a vibrant, responsive, and diverse [community](/dev-zone).

      section5: false


    navbar:
      - title: Install
        url: /install
      - title: Documentation
        url: https://scipy.github.io/devdocs/index.html
      - title: Download
        url: /download
      - title: Mailing Lists
        url: /mailing-lists
      - title: Report bugs
        url: /bug-report
    footer:
      logo: logo.svg
      socialmediatitle: ""
      socialmedia:
      - link: https://github.com/scipy/scipy
        icon: github
      quicklinks:
        column1:
          title: ""
          links:
            - text: Install
              link: /install
            - text: Documentation
              link: https://scipy.github.io/devdocs/index.html
            - text: Citing SciPy
              link: /citing-scipy
            - text: Roadmap
              link: https://scipy.github.io/devdocs/dev/roadmap.html
            - text: Donate
              link: /donations
        column2:
          links:
            - text: About Us
              link: https://scipy.github.io/devdocs/dev/governance/people.html
            - text: Code of Conduct
              link: http://scipy.github.io/devdocs/dev/conduct/code_of_conduct.html
            - text: Developer Zone
              link: /dev-zone
            - text: Mailing Lists
              link: /mailing-lists
            - text: FAQ
              link: /faq
        column3:
          links:
            - text: Get Help
              link: /gethelp
            - text: Terms of Use
              link: /terms
            - text: Privacy
              link: /privacy
            - text: Press Kit
              link: /press-kit
