baseURL: https://scipy.scientific-python.org/
languageCode: en-us
theme: scientific-python-hugo-theme
disableKinds: ["taxonomy", "term"]
DefaultContentLanguage: en
markup:
  goldmark:
    renderer:
      unsafe: true

# Uncomment this to disable the translations for the specified languages.
# This may be useful to be able to merge partial translations without deploying
# them to scipy.org immediately.
# disableLanguages: ["pt", "ja"]

params:
  images:
    - /images/logo.svg
  navColor: blue
  font:
    name: "Lato"
    sizes: [400, 900]
  plausible:
    dataDomain: scipy.org

languages:
  en:
    title: SciPy
    weight: 1
    contentDir: content/en

    languageName: English
    params:
      description: Why SciPy? Fundamental algorithms. Broadly applicable. Foundational. Interoperable. Performant. Open source.
      navbarlogo:
        image: logo.svg
        altText: A blue circle with a snake in the shape of the letter 'S'.
        text: SciPy
        link: /
      hero:
        # Main hero title
        title: SciPy
        # Hero subtitle (optional)
        subtitle: Fundamental algorithms for scientific computing in Python
        # Button text
        buttontext: Get started
        # Where the main hero button links to
        buttonlink: "/install"
        # Hero image (from static/images/___)
        image: logo.svg

      section5: false

      navbar:
        - title: Install
          url: /install
        - title: Documentation
          url: https://docs.scipy.org/doc/scipy/
        - title: Community
          url: /community
        - title: About Us
          url: /about
        - title: Contribute
          url: /contribute
      footer:
        logo: logo.svg
        socialmediatitle: ""
        socialmedia:
          - link: https://github.com/scipy/scipy
            icon: github
          - link: https://x.com/SciPy_team
            icon: x-twitter
        quicklinks:
          column1:
            title: ""
            links:
              - text: Install
                link: /install
              - text: Documentation
                link: https://docs.scipy.org/doc/scipy/
              - text: Citing SciPy
                link: /citing-scipy
              - text: Roadmap
                link: https://scipy.github.io/devdocs/dev/roadmap.html
          column2:
            links:
              - text: About Us
                link: /about
              - text: Community
                link: /community
              - text: SciPy Conference
                link: https://conference.scipy.org/
              - text: Contribute
                link: /contribute
              - text: Code of Conduct
                link: https://docs.scipy.org/doc/scipy/dev/conduct/code_of_conduct.html
          column3:
            links:
              - text: FAQ
                link: /faq
              - text: Terms of Use
                link: /terms
              - text: Privacy
                link: /privacy
              - text: Press Kit
                link: /press-kit
