[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://avatars.githubusercontent.com/u/702934?u=a026c1b1117981cea46e56ba562f3e80dfa71329&v=4"'
alt = 'Avatar of Andrew Nelson'
{{< /image >}}
Andrew Nelson'''
link = 'https://github.com/andyfaff'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://avatars.githubusercontent.com/u/3813847?v=4"'
alt = 'Avatar of Atsushi Sakai'
{{< /image >}}
Atsushi Sakai'''
link = 'https://github.com/AtsushiSakai'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://avatars.githubusercontent.com/u/77272?v=4"'
alt = 'Avatar of Charles Harris'
{{< /image >}}
Charles Harris'''
link = 'https://github.com/charris'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://avatars.githubusercontent.com/u/33071866?v=4"'
alt = 'Avatar of Christoph Baumgarten'
{{< /image >}}
Christoph Baumgarten'''
link = 'https://github.com/chrisb83'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://avatars.githubusercontent.com/u/12721170?u=523b41364ac96519a0abbe367ff96aa82e071755&v=4"'
alt = 'Avatar of Dietrich Brunn'
{{< /image >}}
Dietrich Brunn'''
link = 'https://github.com/DietBru'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://avatars.githubusercontent.com/u/40656107?u=ec1b5e41026e08a37464489f421f0eac3474d1b1&v=4"'
alt = 'Avatar of Daniel Schmitz'
{{< /image >}}
Daniel Schmitz'''
link = 'https://github.com/dschmitz89'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://avatars.githubusercontent.com/u/915037?u=6a27f396c666c5c2172a1cfc7b0d4bbcd0069eed&v=4"'
alt = 'Avatar of Dan Schult'
{{< /image >}}
Dan Schult'''
link = 'https://github.com/dschult'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://avatars.githubusercontent.com/u/2133832?v=4"'
alt = 'Avatar of Evgeni Burovski'
{{< /image >}}
Evgeni Burovski'''
link = 'https://github.com/ev-br'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://avatars.githubusercontent.com/u/6528957?u=b74cdd23ec9edad8546b503b3fe86b927de41c25&v=4"'
alt = 'Avatar of Gregory Lee'
{{< /image >}}
Gregory Lee'''
link = 'https://github.com/grlee77'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://avatars.githubusercontent.com/u/33685575?v=4"'
alt = 'Avatar of h-vetinari'
{{< /image >}}
h-vetinari'''
link = 'https://github.com/h-vetinari'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://avatars.githubusercontent.com/u/1303842?u=b5e1e287787b49216b2942bf4b5880e4b91b8d90&v=4"'
alt = 'Avatar of Ilhan Polat'
{{< /image >}}
Ilhan Polat'''
link = 'https://github.com/ilayn'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://avatars.githubusercontent.com/u/60778417?u=29f920eaf5b41b5bdfbde65631d0581a0bf870b8&v=4"'
alt = 'Avatar of Jake Bowhay'
{{< /image >}}
Jake Bowhay'''
link = 'https://github.com/j-bowhay'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://avatars.githubusercontent.com/u/440735?v=4"'
alt = 'Avatar of Josef Perktold'
{{< /image >}}
Josef Perktold'''
link = 'https://github.com/josef-pkt'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://avatars.githubusercontent.com/u/30074037?u=c2549c85c82266302c71aef5c20446871323d91b&v=4"'
alt = 'Avatar of Kai Striega'
{{< /image >}}
Kai Striega'''
link = 'https://github.com/Kai-Striega'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://avatars.githubusercontent.com/u/2365790?v=4"'
alt = 'Avatar of Eric Larson'
{{< /image >}}
Eric Larson'''
link = 'https://github.com/larsoner'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://avatars.githubusercontent.com/u/51488791?u=57da3ab3e223374ed21bad2b965fced84e6a397c&v=4"'
alt = 'Avatar of Lucas Colley'
{{< /image >}}
Lucas Colley'''
link = 'https://github.com/lucascolley'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://avatars.githubusercontent.com/u/67612?v=4"'
alt = 'Avatar of Matthew Brett'
{{< /image >}}
Matthew Brett'''
link = 'https://github.com/matthew-brett'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://avatars.githubusercontent.com/u/28734319?u=47aabb43a32b6e7f62d73a75f0b51e3c640a3d2c&v=4"'
alt = 'Avatar of Nicholas McKibben'
{{< /image >}}
Nicholas McKibben'''
link = 'https://github.com/mckib2'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://avatars.githubusercontent.com/u/6570539?u=cfb3e218754e85c4fac18064d7cfdce0b67ddaa6&v=4"'
alt = 'Avatar of Matt Haberland'
{{< /image >}}
Matt Haberland'''
link = 'https://github.com/mdhaber'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://avatars.githubusercontent.com/u/3949932?u=aacac68df60d2cf64c17c7e5aa17adf8b738aa7b&v=4"'
alt = 'Avatar of Melissa Weber Mendonça'
{{< /image >}}
Melissa Weber Mendonça'''
link = 'https://github.com/melissawm'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://avatars.githubusercontent.com/u/666402?u=08764de13b66ac2a20ff7fe3913c9f73cb1f8578&v=4"'
alt = 'Avatar of Nick ODell'
{{< /image >}}
Nick ODell'''
link = 'https://github.com/nickodell'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://avatars.githubusercontent.com/u/7074023?u=a20dd05a809e6865c29deca04e5cbb0c6f9e5433&v=4"'
alt = 'Avatar of Nikolay Mayorov'
{{< /image >}}
Nikolay Mayorov'''
link = 'https://github.com/nmayorov'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://avatars.githubusercontent.com/u/82855?v=4"'
alt = 'Avatar of CJ Carey'
{{< /image >}}
CJ Carey'''
link = 'https://github.com/perimosocordiae'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://avatars.githubusercontent.com/u/15134881?v=4"'
alt = 'Avatar of Josh Wilson'
{{< /image >}}
Josh Wilson'''
link = 'https://github.com/person142'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://avatars.githubusercontent.com/u/13238737?v=4"'
alt = 'Avatar of peterbell10'
{{< /image >}}
peterbell10'''
link = 'https://github.com/peterbell10'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://avatars.githubusercontent.com/u/35046?v=4"'
alt = 'Avatar of Pauli Virtanen'
{{< /image >}}
Pauli Virtanen'''
link = 'https://github.com/pv'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://avatars.githubusercontent.com/u/23403152?v=4"'
alt = 'Avatar of Paul van Mulbregt'
{{< /image >}}
Paul van Mulbregt'''
link = 'https://github.com/pvanmulbregt'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://avatars.githubusercontent.com/u/98330?u=22a023f8d191ba200ab13d476c83860d015cc9fe&v=4"'
alt = 'Avatar of Ralf Gommers'
{{< /image >}}
Ralf Gommers'''
link = 'https://github.com/rgommers'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://avatars.githubusercontent.com/u/46135?u=305a96a4778daecacbc8ec97ac25a48099a239cc&v=4"'
alt = 'Avatar of Robert Kern'
{{< /image >}}
Robert Kern'''
link = 'https://github.com/rkern'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://avatars.githubusercontent.com/u/5400493?u=64e192c8183394028227beef8d180cc9a089b318&v=4"'
alt = 'Avatar of Lucas Roberts'
{{< /image >}}
Lucas Roberts'''
link = 'https://github.com/rlucas7'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://avatars.githubusercontent.com/u/45071?u=ef2af0a29229833cd2ae0e5aeb90283881e8c1e0&v=4"'
alt = 'Avatar of Stefan van der Walt'
{{< /image >}}
Stefan van der Walt'''
link = 'https://github.com/stefanv'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://avatars.githubusercontent.com/u/1953382?u=5df9d41ad2a6d526e7daeec06225274905e7e660&v=4"'
alt = 'Avatar of Albert Steppi'
{{< /image >}}
Albert Steppi'''
link = 'https://github.com/steppi'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://avatars.githubusercontent.com/u/67928790?u=e85f64cbd3fa3f43b87946e350812d5d77391f82&v=4"'
alt = 'Avatar of thalassemia'
{{< /image >}}
thalassemia'''
link = 'https://github.com/thalassemia'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://avatars.githubusercontent.com/u/43181252?v=4"'
alt = 'Avatar of Tirth Patel'
{{< /image >}}
Tirth Patel'''
link = 'https://github.com/tirthasheshpatel'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://avatars.githubusercontent.com/u/23188539?u=64445b52dbf3f75de8006ed4264fdd2afaed97a3&v=4"'
alt = 'Avatar of Pamphile Roy'
{{< /image >}}
Pamphile Roy'''
link = 'https://github.com/tupui'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://avatars.githubusercontent.com/u/7903078?u=2762d9ff13b992dc635f8f190a17f9a90cddfae1&v=4"'
alt = 'Avatar of Tyler Reddy'
{{< /image >}}
Tyler Reddy'''
link = 'https://github.com/tylerjereddy'

[[item]]
type = 'card'
classcard = 'text-center'
body = '''{{< image >}}
src = 'https://avatars.githubusercontent.com/u/321463?v=4"'
alt = 'Avatar of Warren Weckesser'
{{< /image >}}
Warren Weckesser'''
link = 'https://github.com/WarrenWeckesser'
